cur.execute("INSERT INTO store VALUES ('Pen', 11, 22.5 )")
cur.execute("INSERT INTO store VALUES ('Carrom Board', 13, 13.5 )")
cur.execute("INSERT INTO store VALUES ('Baseball bat', 20, 43.5 )")
cur.execute("INSERT INTO store VALUES ('Football', 23, 25.5 )")
cur.execute("INSERT INTO store VALUES ('Bat', 50, 24.5 )")
cur.execute("INSERT INTO store VALUES ('Racqu et', 60, 28.5 )")
cur.execute("INSERT INTO store VALUES ('Wheel', 50, 33.5 )")
cur.execute("INSERT INTO store VALUES ('Hat', 14, 53.5 )")
cur.execute("INSERT INTO store VALUES ('Cap', 10, 63.5 )")
print(cur.execute("SELECT quantity FROM store WHERE price <= 30"))